import { initializeApp, getApps, getApp } from 'firebase/app';
import { 
  getAuth, 
  GoogleAuthProvider, 
  signInWithPopup, 
  signInWithEmailAndPassword, 
  createUserWithEmailAndPassword, 
  sendPasswordResetEmail,
  updateProfile,
  signOut as fbSignOut, 
  onAuthStateChanged,
  type User 
} from 'firebase/auth';
import { 
  getFirestore, 
  doc, 
  getDoc, 
  setDoc, 
  collection, 
  getDocs, 
  serverTimestamp 
} from 'firebase/firestore';
import type { UserStockState } from '../types';
import firebaseAppletConfig from '../../firebase-applet-config.json';

// Import configuration generated by AI Studio
const config: any = firebaseAppletConfig || {};

const firebaseApp = getApps().length === 0 ? initializeApp(config) : getApp();

export const auth = getAuth(firebaseApp);
export const googleProvider = new GoogleAuthProvider();

// Custom database ID support from AI Studio
export const db = config.firestoreDatabaseId && config.firestoreDatabaseId !== '(default)'
  ? getFirestore(firebaseApp, config.firestoreDatabaseId)
  : getFirestore(firebaseApp);

export { onAuthStateChanged, type User };

export async function loginWithGoogle(): Promise<User> {
  const result = await signInWithPopup(auth, googleProvider);
  return result.user;
}

export async function loginWithEmail(email: string, pass: string): Promise<User> {
  const result = await signInWithEmailAndPassword(auth, email.trim(), pass);
  return result.user;
}

export async function registerWithEmail(email: string, pass: string, displayName?: string): Promise<User> {
  const result = await createUserWithEmailAndPassword(auth, email.trim(), pass);
  if (displayName && result.user) {
    try {
      await updateProfile(result.user, { displayName: displayName.trim() });
    } catch (e) {
      console.warn('Could not set displayName on user profile', e);
    }
  }
  return result.user;
}

export async function resetPasswordWithEmail(email: string): Promise<void> {
  await sendPasswordResetEmail(auth, email.trim());
}

export async function logoutUser(): Promise<void> {
  await fbSignOut(auth);
}

export function getFirebaseAuthErrorMessage(error: any): string {
  if (!error) return 'An unexpected error occurred. Please try again.';
  const code = error.code || '';
  switch (code) {
    case 'auth/invalid-email':
      return 'Please enter a valid email address.';
    case 'auth/user-disabled':
      return 'This account has been disabled. Please contact support.';
    case 'auth/user-not-found':
      return 'No account exists with this email address. Please create an account.';
    case 'auth/wrong-password':
    case 'auth/invalid-credential':
      return 'Incorrect email or password. Please verify and try again.';
    case 'auth/email-already-in-use':
      return 'An account with this email address already exists. Please sign in instead.';
    case 'auth/operation-not-allowed':
    case 'auth/admin-restricted-operation':
      return 'This sign-in method is not enabled. Please sign in with Google.';
    case 'auth/weak-password':
      return 'The password is too weak. Please use at least 6 characters.';
    case 'auth/missing-password':
      return 'Please enter your password.';
    case 'auth/popup-closed-by-user':
      return 'The sign-in window was closed before completing.';
    case 'auth/too-many-requests':
      return 'Access temporarily blocked due to multiple failed attempts. Please try again later.';
    case 'auth/network-request-failed':
      return 'Network connection failed. Please check your internet connection.';
    default:
      return error.message || 'Authentication failed. Please check your credentials.';
  }
}

// ----------------------------------------------------
// Firestore Watchlist Persistence
// ----------------------------------------------------

export async function getUserWatchlist(userId: string): Promise<string[]> {
  if (!userId) {
    throw new Error('[Firestore] getUserWatchlist requires an authenticated userId.');
  }

  const watchlistRef = doc(db, 'users', userId, 'watchlists', 'default');
  const snap = await getDoc(watchlistRef);
  if (snap.exists() && snap.data()?.tickers) {
    return snap.data().tickers as string[];
  }

  // Default initial watchlist for new users (NVIDIA, Apple, Tesla, Microsoft)
  const defaultList = ['NVDA', 'AAPL', 'TSLA', 'MSFT'];
  await saveUserWatchlist(userId, defaultList);
  return defaultList;
}

export async function saveUserWatchlist(userId: string, tickers: string[]): Promise<void> {
  if (!userId) {
    throw new Error('[Firestore] saveUserWatchlist requires an authenticated userId.');
  }

  const watchlistRef = doc(db, 'users', userId, 'watchlists', 'default');
  await setDoc(watchlistRef, {
    tickers,
    updatedAt: new Date().toISOString(),
  }, { merge: true });
}

// ----------------------------------------------------
// Firestore "Since You Last Checked" State Persistence
// ----------------------------------------------------

export async function getUserStockStates(userId: string): Promise<Record<string, UserStockState>> {
  if (!userId) {
    throw new Error('[Firestore] getUserStockStates requires an authenticated userId.');
  }

  const states: Record<string, UserStockState> = {};
  const statesCol = collection(db, 'users', userId, 'stockStates');
  const snap = await getDocs(statesCol);
  snap.forEach((d) => {
    states[d.id] = d.data() as UserStockState;
  });
  return states;
}

export async function saveUserStockState(userId: string, state: UserStockState): Promise<void> {
  if (!userId) {
    throw new Error('[Firestore] saveUserStockState requires an authenticated userId.');
  }

  const stateRef = doc(db, 'users', userId, 'stockStates', state.ticker);
  await setDoc(stateRef, {
    ...state,
    updatedAt: serverTimestamp(),
  }, { merge: true });
}
