import { initializeApp, getApps, getApp } from 'firebase/app';
import { 
  getAuth, 
  GoogleAuthProvider, 
  signInWithPopup, 
  signInWithEmailAndPassword, 
  createUserWithEmailAndPassword, 
  signOut as fbSignOut, 
  signInAnonymously,
  onAuthStateChanged,
  type User 
} from 'firebase/auth';
import { 
  getFirestore, 
  doc, 
  getDoc, 
  setDoc, 
  collection, 
  getDocs,
  serverTimestamp 
} from 'firebase/firestore';
import type { UserStockState } from '../types';
import firebaseAppletConfig from '../../firebase-applet-config.json';

// Import configuration generated by AI Studio
const config: any = firebaseAppletConfig || {};

const firebaseApp = getApps().length === 0 ? initializeApp(config) : getApp();

export const auth = getAuth(firebaseApp);
export const googleProvider = new GoogleAuthProvider();

// Custom database ID support from AI Studio
export const db = config.firestoreDatabaseId && config.firestoreDatabaseId !== '(default)'
  ? getFirestore(firebaseApp, config.firestoreDatabaseId)
  : getFirestore(firebaseApp);

export { onAuthStateChanged, type User };

export async function loginWithGoogle(): Promise<User> {
  const result = await signInWithPopup(auth, googleProvider);
  return result.user;
}

export async function loginWithEmail(email: string, pass: string): Promise<User> {
  const result = await signInWithEmailAndPassword(auth, email, pass);
  return result.user;
}

export async function registerWithEmail(email: string, pass: string): Promise<User> {
  const result = await createUserWithEmailAndPassword(auth, email, pass);
  return result.user;
}

export async function loginAsGuestEvaluator(): Promise<User> {
  try {
    const result = await signInAnonymously(auth);
    return result.user;
  } catch (err) {
    console.warn('Anonymous auth failed, returning demo mock user', err);
    throw err;
  }
}

export async function logoutUser(): Promise<void> {
  await fbSignOut(auth);
}

// ----------------------------------------------------
// Firestore Watchlist Persistence
// ----------------------------------------------------

export async function getUserWatchlist(userId: string): Promise<string[]> {
  try {
    const watchlistRef = doc(db, 'users', userId, 'watchlists', 'default');
    const snap = await getDoc(watchlistRef);
    if (snap.exists() && snap.data()?.tickers) {
      return snap.data().tickers as string[];
    }
  } catch (e) {
    console.warn('Firestore fetch failed, checking local fallback', e);
  }

  // Local fallback persistence
  const local = localStorage.getItem(`pulse_wl_${userId}`);
  if (local) {
    try {
      return JSON.parse(local);
    } catch {}
  }

  // Default initial watchlist for new users (NVIDIA, Apple, Tesla, Microsoft)
  const defaultList = ['NVDA', 'AAPL', 'TSLA', 'MSFT'];
  try {
    await saveUserWatchlist(userId, defaultList);
  } catch {}
  return defaultList;
}

export async function saveUserWatchlist(userId: string, tickers: string[]): Promise<void> {
  try {
    localStorage.setItem(`pulse_wl_${userId}`, JSON.stringify(tickers));
    const watchlistRef = doc(db, 'users', userId, 'watchlists', 'default');
    await setDoc(watchlistRef, {
      tickers,
      updatedAt: new Date().toISOString(),
    }, { merge: true });
  } catch (e) {
    console.warn('Could not persist watchlist to Firestore', e);
  }
}

// ----------------------------------------------------
// Firestore "Since You Last Checked" State Persistence
// ----------------------------------------------------

export async function getUserStockStates(userId: string): Promise<Record<string, UserStockState>> {
  const states: Record<string, UserStockState> = {};
  
  // Try Firestore first
  try {
    const statesCol = collection(db, 'users', userId, 'stockStates');
    const snap = await getDocs(statesCol);
    snap.forEach((d) => {
      states[d.id] = d.data() as UserStockState;
    });
    if (Object.keys(states).length > 0) {
      localStorage.setItem(`pulse_states_${userId}`, JSON.stringify(states));
      return states;
    }
  } catch (e) {
    console.warn('Firestore stockStates fetch error', e);
  }

  // Local storage fallback
  const local = localStorage.getItem(`pulse_states_${userId}`);
  if (local) {
    try {
      return JSON.parse(local);
    } catch {}
  }

  return states;
}

export async function saveUserStockState(userId: string, state: UserStockState): Promise<void> {
  try {
    // Save to local cache
    const currentLocal = localStorage.getItem(`pulse_states_${userId}`);
    const parsed = currentLocal ? JSON.parse(currentLocal) : {};
    parsed[state.ticker] = state;
    localStorage.setItem(`pulse_states_${userId}`, JSON.stringify(parsed));

    // Save to Firestore
    const stateRef = doc(db, 'users', userId, 'stockStates', state.ticker);
    await setDoc(stateRef, {
      ...state,
      updatedAt: serverTimestamp(),
    }, { merge: true });
  } catch (e) {
    console.warn(`Could not save stock state for ${state.ticker}`, e);
  }
}
