/**
 * Pulse — Demo & Simulator Data Universe
 * 
 * STRICT ARCHITECTURAL RULE:
 * This file contains mock data strictly reserved for DEMO / SIMULATOR MODE.
 * It is NEVER used as a fallback for real API failures in Real Mode.
 * All quotes generated from this universe are tagged with:
 * isDemo: true, source: 'Demo Simulator'
 */

import type { StockQuote, NewsArticle, StockEvent, MarketFreshness } from '../../src/types';

export interface DemoUniverseItem extends Omit<StockQuote, 'price' | 'change' | 'percentChange' | 'volume' | 'updatedAt'> {
  basePrice: number;
  baseVolume: number;
  histMean: number;
  histStdDev: number;
}

export const DEMO_STOCK_UNIVERSE: Record<string, DemoUniverseItem> = {
  NVDA: {
    ticker: 'NVDA',
    name: 'NVIDIA Corporation',
    exchange: 'NASDAQ',
    currency: 'USD',
    previousClose: 160.00,
    averageVolume: 48500000,
    normalDailyRangePercent: 2.2,
    dayHigh: 162.40,
    dayLow: 158.90,
    fiftyTwoWeekHigh: 175.00,
    fiftyTwoWeekLow: 85.00,
    marketCap: '$3.94T',
    sector: 'Semiconductors',
    source: 'Demo Simulator',
    freshness: 'live',
    basePrice: 160.10,
    baseVolume: 51200000,
    histMean: 155.40,
    histStdDev: 6.20,
  },
  TSLA: {
    ticker: 'TSLA',
    name: 'Tesla, Inc.',
    exchange: 'NASDAQ',
    currency: 'USD',
    previousClose: 245.50,
    averageVolume: 65000000,
    normalDailyRangePercent: 3.5,
    dayHigh: 248.10,
    dayLow: 241.20,
    fiftyTwoWeekHigh: 271.00,
    fiftyTwoWeekLow: 138.80,
    marketCap: '$782B',
    sector: 'Automotive & Clean Tech',
    source: 'Demo Simulator',
    freshness: 'live',
    basePrice: 242.80,
    baseVolume: 67100000,
    histMean: 238.50,
    histStdDev: 14.80,
  },
  AAPL: {
    ticker: 'AAPL',
    name: 'Apple Inc.',
    exchange: 'NASDAQ',
    currency: 'USD',
    previousClose: 228.40,
    averageVolume: 42000000,
    normalDailyRangePercent: 1.1,
    dayHigh: 229.80,
    dayLow: 227.60,
    fiftyTwoWeekHigh: 237.23,
    fiftyTwoWeekLow: 164.08,
    marketCap: '$3.45T',
    sector: 'Consumer Electronics',
    source: 'Demo Simulator',
    freshness: 'live',
    basePrice: 228.85,
    baseVolume: 39500000,
    histMean: 224.10,
    histStdDev: 5.40,
  },
  MSFT: {
    ticker: 'MSFT',
    name: 'Microsoft Corporation',
    exchange: 'NASDAQ',
    currency: 'USD',
    previousClose: 448.20,
    averageVolume: 19500000,
    normalDailyRangePercent: 1.2,
    dayHigh: 451.00,
    dayLow: 446.80,
    fiftyTwoWeekHigh: 468.35,
    fiftyTwoWeekLow: 388.00,
    marketCap: '$3.33T',
    sector: 'Cloud & Enterprise Software',
    source: 'Demo Simulator',
    freshness: 'live',
    basePrice: 449.10,
    baseVolume: 18200000,
    histMean: 442.00,
    histStdDev: 8.50,
  },
  AMZN: {
    ticker: 'AMZN',
    name: 'Amazon.com, Inc.',
    exchange: 'NASDAQ',
    currency: 'USD',
    previousClose: 186.50,
    averageVolume: 34000000,
    normalDailyRangePercent: 1.8,
    dayHigh: 188.40,
    dayLow: 185.10,
    fiftyTwoWeekHigh: 201.20,
    fiftyTwoWeekLow: 144.05,
    marketCap: '$1.94T',
    sector: 'E-Commerce & Cloud Computing',
    source: 'Demo Simulator',
    freshness: 'live',
    basePrice: 187.30,
    baseVolume: 31500000,
    histMean: 182.20,
    histStdDev: 6.80,
  },
  GOOGL: {
    ticker: 'GOOGL',
    name: 'Alphabet Inc.',
    exchange: 'NASDAQ',
    currency: 'USD',
    previousClose: 164.20,
    averageVolume: 22000000,
    normalDailyRangePercent: 1.5,
    dayHigh: 165.80,
    dayLow: 163.50,
    fiftyTwoWeekHigh: 191.75,
    fiftyTwoWeekLow: 129.40,
    marketCap: '$2.02T',
    sector: 'Internet & AI',
    source: 'Demo Simulator',
    freshness: 'live',
    basePrice: 164.70,
    baseVolume: 21800000,
    histMean: 161.50,
    histStdDev: 5.90,
  },
  META: {
    ticker: 'META',
    name: 'Meta Platforms, Inc.',
    exchange: 'NASDAQ',
    currency: 'USD',
    previousClose: 590.00,
    averageVolume: 14000000,
    normalDailyRangePercent: 2.1,
    dayHigh: 596.50,
    dayLow: 587.20,
    fiftyTwoWeekHigh: 615.00,
    fiftyTwoWeekLow: 279.00,
    marketCap: '$1.49T',
    sector: 'Social Media & Virtual Reality',
    source: 'Demo Simulator',
    freshness: 'live',
    basePrice: 592.40,
    baseVolume: 13500000,
    histMean: 574.00,
    histStdDev: 16.50,
  },
  INFY: {
    ticker: 'INFY',
    name: 'Infosys Limited',
    exchange: 'NSE',
    currency: 'INR',
    previousClose: 1920.00,
    averageVolume: 6200000,
    normalDailyRangePercent: 1.4,
    dayHigh: 1938.00,
    dayLow: 1912.00,
    fiftyTwoWeekHigh: 1995.00,
    fiftyTwoWeekLow: 1358.00,
    marketCap: '₹7.98L Cr',
    sector: 'IT Services & Consulting',
    source: 'Demo Simulator',
    freshness: 'live',
    basePrice: 1928.50,
    baseVolume: 5900000,
    histMean: 1890.00,
    histStdDev: 42.00,
  },
  RELIANCE: {
    ticker: 'RELIANCE',
    name: 'Reliance Industries Limited',
    exchange: 'NSE',
    currency: 'INR',
    previousClose: 2980.00,
    averageVolume: 7800000,
    normalDailyRangePercent: 1.3,
    dayHigh: 2995.00,
    dayLow: 2965.00,
    fiftyTwoWeekHigh: 3217.90,
    fiftyTwoWeekLow: 2221.05,
    marketCap: '₹20.16L Cr',
    sector: 'Conglomerate & Energy',
    source: 'Demo Simulator',
    freshness: 'live',
    basePrice: 2985.20,
    baseVolume: 7400000,
    histMean: 2940.00,
    histStdDev: 55.00,
  },
  TCS: {
    ticker: 'TCS',
    name: 'Tata Consultancy Services',
    exchange: 'NSE',
    currency: 'INR',
    previousClose: 4250.00,
    averageVolume: 2400000,
    normalDailyRangePercent: 1.2,
    dayHigh: 4275.00,
    dayLow: 4230.00,
    fiftyTwoWeekHigh: 4592.25,
    fiftyTwoWeekLow: 3313.00,
    marketCap: '₹15.38L Cr',
    sector: 'IT Services & Consulting',
    source: 'Demo Simulator',
    freshness: 'live',
    basePrice: 4260.00,
    baseVolume: 2300000,
    histMean: 4180.00,
    histStdDev: 68.00,
  },
};

export const DEMO_NEWS_DATABASE: NewsArticle[] = [
  {
    id: 'demo-news-nvda-1',
    ticker: 'NVDA',
    title: '[DEMO] NVIDIA Unveils Next-Gen Blackwell Ultra Architecture Ahead of Schedule',
    source: 'Demo Wire (Simulated)',
    url: 'https://example.com/demo/nvda-1',
    publishedAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    relevance: 0.95,
    sentiment: 'positive',
  },
  {
    id: 'demo-news-tsla-1',
    ticker: 'TSLA',
    title: '[DEMO] NHTSA Expands Review of Full Self-Driving Software Deployments',
    source: 'Demo Wire (Simulated)',
    url: 'https://example.com/demo/tsla-1',
    publishedAt: new Date(Date.now() - 120 * 60 * 1000).toISOString(),
    relevance: 0.92,
    sentiment: 'negative',
  },
];

export const DEMO_EVENTS_DATABASE: StockEvent[] = [
  {
    id: 'demo-evt-nvda-1',
    ticker: 'NVDA',
    type: 'earnings',
    title: '[DEMO] Q3 FY26 Earnings Conference Call',
    description: 'Simulated earnings report scenario',
    impactScore: 0.95,
    timestamp: new Date().toISOString(),
  },
];
